### ISSUE TITLE
`Auth0RemixTypes` is not getting bundled on package

### ISSUE THREAD

**Issue by danestves** [meza/auth0-remix-server#10]
### What happened?

The package doesn't have most of the types because the `Auth0RemixTypes` is not bundled on the package

![](https://user-images.githubusercontent.com/31737273/225079335-db61d7ed-f826-4cc3-ad09-aff0b30939d0.png)

### What did you expect to happen?

All the needed files must be bundled on the npm package

### What version of Remix are you using?

1.14.1

**Comment by meza** [comment]
Thanks, looking into it! 👍🏻

**Comment by meza** [comment]
We messed up the "fix" for this. New one en route

**Comment by danestves** [comment]
> We messed up the "fix" for this. New one en route

lol I was just connecting to almost update the package haha!

**Comment by meza** [comment]
Sorry about that. This current state of ESM/CJS is doing my head in. Hopefully got it right on the @next - publishing momentarily with #15

**Comment by meza** [comment]
Seems promising. Want to give this version a go and see if it works for you too, @danestves?

**Comment by meza** [comment]
nevermind, something's not right -.-'

**Comment by meza** [comment]
`1.2.3-next.2` might be the one. It's behaving on my test project now 🤞🏻

**Comment by danestves** [comment]
> `1.2.3-next.2` might be the one. It's behaving on my test project now 🤞🏻

Yeah, is working from my side too
