### ISSUE TITLE
Adding several parameters to authorize and handleCallback

### ISSUE THREAD

**Issue by njpearman** [meza/auth0-remix-server#138]
### I have checked for similar

- [X] I have searched for my issue and did not find it

### Not a bug

- [X] I swear this is an actual feature request

### Why?

Hi 👋 I'm opening an issue that covers three specific types of parameters that we are looking expose in the `auth0-remix-server` package. They are all broadly the same type of change so I thought I'd open one issue to cover all three but can split them if necessary. Here they are:

Auth0 allows various options when calling to authorize a user. Currently, `prompt` and `connection` ([as documented in request parameters here](https://auth0.com/docs/api/authentication#authorize-application)) aren't supported in `auth0-remix-server` but we need them for our auth flow as it gives us finer control over what approval screens get presented to our users.

We also need to be able to override the `failedRedirectURL` to cater for slightly different paths through our auth flow, as we want failure for a user coming from one location to be different from a user coming from a different location.

The third thing is that we need to be able to persist several arbitrary parameters over the course of the auth flow so that they are available at the end of the flow. Specifically, we are using a PKCE flow and we have to retain the `code` and `state` value returned by Auth0 until the end of the flow when they are used to get an access token.

### What?

We've already forked the repo and implemented what we need. These are adding several new properties to the `AuthorizeOptions` and `HandleCallbackOptions` interfaces, and then incorporating these in the requests built up in `authorize` and `handleCallback`.

I can open a single pull request to cover all three specifics described above, or three separate pull requests.

**Comment by meza** [comment]
Hey @njpearman, great points!

If you could split them up to separate PRs, that might be simpler to grasp when reviewing! :)

I'll have time during this week and go through them all

**Comment by meza** [comment]
Hey @njpearman for the failed redirect, isn't the `failedLoginRedirect` option in the `Auth0RemixServer` options good enough?

**Comment by meza** [comment]
@njpearman Most of these should now be released with [2.1.0](https://github.com/meza/auth0-remix-server/releases/tag/v2.1.0)

The only outstanding question is why you would need to override the prompt directly.
As far as I'm aware the 3 states of it is not set, "login" or "none".

I've now incorporate the `silentAuth` parameter in the AuthorizationOptions. Is that enough or was there a specific usecase that requires you to set it to something else?

**Comment by njpearman** [comment]
@meza, we don't need direct access to `prompt`, just a way to set it to `'none'`, which `silentAuth` should give us. Thanks for that 🎉

Thanks also for adding `onFailedRedirect`. I expect you already understand why I wanted to add it but just for completeness, `failedLoginRedirect` doesn't satisfy our needs as it isn't dynamic enough. The suggestion to add `onFailedRedirect` gives us the opportunity to build a URL / path that includes URL params only known when we call `handleCallback` and override `failedLoginRedirect`. As far as I understand, we can't use `failedLoginRedirect` in this way as we'd have to create a new `Auth0RemixServer`.

**Comment by njpearman** [comment]
This all seems to be working fine in our integration. Thanks for the merge!

**Comment by meza** [comment]
Thanks, great to hear!

I've also added a new thing that might be of interest:

https://github.com/meza/auth0-remix-server/blob/main/README.md#session-storage-strategies

It's particularly useful id you're using a DB as the session backend
